---
# expose in cluster on port 80
# expose in the node on port 31080
# make your ingress or reverse proxy point to 31080 port toaccess app
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: koel
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31080
      targetPort: 80
